GET http://localhost:3000
Accept: application/json

###

GET http://localhost:3000/health
Accept: application/json

###

POST http://localhost:3000/api/shopback/create-dynamic-qr-order
Content-Type: application/json

{
    "posId": "110e6f8b-20a8-42fe-9577-8b48b3bd19d1",
    "country": "MY",
    "amount": 4000,
    "currency": "MYR",
    "qrType": "payload"
}

###

POST http://localhost:3000/api/shopback/scan-consumer-qr
Content-Type: application/json

{
  "posId": "110e6f8b-20a8-42fe-9577-8b48b3bd19d1",
  "country": "MY",
  "amount": 4000,
  "currency": "MYR",
  "consumerQrPayload": "77898366NXVU7XTS15791111"
}

###

GET http://localhost:3000/api/shopback/order-status/202507081717296665

###

POST http://localhost:3000/api/shopback/order-refund/202507090231564103
Content-Type: application/json

{
    "amount": 2000,
    "reason": "Customer requested refund",
    "referenceId": "10733713-7bec-4ae9-bfe8-b9fc877663af"
}

###

POST http://localhost:3000/api/shopback/cancel-order/10733713-7bec-4ae9-bfe8-b9fc877663af
Content-Type: application/json

{
    "reason": "Order cancelled by merchant"
}

###



